## price pattern recognization

In [1]:
import talib
import pandas as pd
import tushare as tu
import matplotlib.pyplot as plt
%matplotlib inline
%pylab inline
pylab.rcParams['figure.figsize'] = (15, 9)   # Change the size of plots

Populating the interactive namespace from numpy and matplotlib


In [26]:
df_ldkg = tu.get_hist_data('600606')

In [3]:
df_ldkg.head()

open  high  close   low     volume  price_change  p_change    ma5  \
date                                                                            
2016-12-28  8.73  8.77   8.65  8.64  355185.38         -0.11     -1.26  8.808   
2016-12-27  8.72  8.95   8.76  8.69  431607.25          0.01      0.11  8.890   
2016-12-26  8.85  8.85   8.75  8.53  579355.31         -0.12     -1.35  8.942   
2016-12-23  9.01  9.02   8.87  8.83  530662.25         -0.14     -1.55  8.996   
2016-12-22  9.06  9.06   9.01  8.97  322022.34         -0.05     -0.55  9.046   

             ma10   ma20      v_ma5     v_ma10      v_ma20  turnover  
date                                                                  
2016-12-28  8.927  9.164  443766.51  417920.77   792337.65      1.10  
2016-12-27  8.958  9.211  443716.32  435737.33   833566.26      1.34  
2016-12-26  8.989  9.250  417276.39  448421.16   883816.74      1.80  
2016-12-23  9.016  9.300  373586.07  530896.46   938975.96      1.65  
2016-12-22  9.068  9.345  372427.84  558378.64  1011930.27      1.00

In [28]:
ldkg = df_ldkg[['open','high','close','low']]#input for pattern recognization
ldkg.head()

open  high  close   low
date                               
2016-12-28  8.73  8.77   8.65  8.64
2016-12-27  8.72  8.95   8.76  8.69
2016-12-26  8.85  8.85   8.75  8.53
2016-12-23  9.01  9.02   8.87  8.83
2016-12-22  9.06  9.06   9.01  8.97

In [5]:
print talib.get_function_groups().keys()

['Pattern Recognition', 'Volume Indicators', 'Math Transform', 'Math Operators', 'Cycle Indicators', 'Volatility Indicators', 'Overlap Studies', 'Statistic Functions', 'Momentum Indicators', 'Price Transform']


In [6]:
?talib.CDLDOJI

In [7]:
doji=talib.CDLDOJI(ldkg['open'].values,ldkg['high'].values,ldkg['low'].values,ldkg['close'].values)
doji

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 100,   0,   0,
       100, 100,   0, 100,   0,   0,   0,   0, 100,   0,   0, 100,   0,
         0,   0,   0,   0,   0,   0,   0, 100,   0,   0,   0,   0,   0,
         0,   0,   0, 100,   0,   0, 100,   0,   0,   0,   0,   0,   0,
         0,   0, 100,   0, 100, 100,   0, 100,   0,   0,   0,   0,   0,
         0,   0, 100,   0,   0,   0,   0, 100,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
       100,   0,   0,   0,   0,   0, 100,   0,   0,   0,   0,   0,   0,
         0, 100,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0, 100,   0,   0,   0,   0,   0,   0,   0, 100,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0, 100,   0,   0,   0,
       100,   0,   0,   0,   0, 100,   0,   0,   0,   0,   0,   

In [8]:
reload(pandaStock)
pandaStock.pandas_candlestick_ohlc(ldkg.iloc[29*13:30*13])

NameError: name 'pandaStock' is not defined

In [ ]:
patternFun=talib.get_function_groups()['Pattern Recognition']
para = "(%s['open'].values,%s['high'].values,%s['low'].values,%s['close'].values)" %tuple(['ldkg']*4)
para

In [9]:
patterFunStr=map(lambda x: "talib.%s"%x+para, patternFun)
patterFunStr[0]

NameError: name 'patternFun' is not defined

In [10]:
def patterns(ohcl):
    patternFun=talib.get_function_groups()['Pattern Recognition']
    input = [ohcl['open'].values,ohcl['high'].values,ohcl['low'].values,ohcl['close'].values]
    for f in patternFun:
        ohcl[f]=eval("talib.%s(*input)"%f)
#patterns(ldkg)

/usr/local/lib/python2.7/site-packages/ipykernel/__main__.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


In [29]:
import patternRecognize
patternRecognize.patterns(ldkg)
ldkg.head()

open  high  close   low  CDL2CROWS  CDL3BLACKCROWS  CDL3INSIDE  \
date                                                                         
2016-12-28  8.73  8.77   8.65  8.64          0               0           0   
2016-12-27  8.72  8.95   8.76  8.69          0               0           0   
2016-12-26  8.85  8.85   8.75  8.53          0               0           0   
2016-12-23  9.01  9.02   8.87  8.83          0               0           0   
2016-12-22  9.06  9.06   9.01  8.97          0               0           0   

            CDL3LINESTRIKE  CDL3OUTSIDE  CDL3STARSINSOUTH  \
date                                                        
2016-12-28               0            0                 0   
2016-12-27               0            0                 0   
2016-12-26               0            0                 0   
2016-12-23               0            0                 0   
2016-12-22               0            0                 0   

                   ...           CDLSPINNINGTOP  CDLSTALLEDPATTERN  \
date               ...                                               
2016-12-28         ...                        0                  0   
2016-12-27         ...                        0                  0   
2016-12-26         ...                        0                  0   
2016-12-23         ...                        0                  0   
2016-12-22         ...                        0                  0   

            CDLSTICKSANDWICH  CDLTAKURI  CDLTASUKIGAP  CDLTHRUSTING  \
date                                                                  
2016-12-28                 0          0             0             0   
2016-12-27                 0          0             0             0   
2016-12-26                 0          0             0             0   
2016-12-23                 0          0             0             0   
2016-12-22                 0          0             0             0   

            CDLTRISTAR  CDLUNIQUE3RIVER  CDLUPSIDEGAP2CROWS  \
date                                                          
2016-12-28           0                0                   0   
2016-12-27           0                0                   0   
2016-12-26           0                0                   0   
2016-12-23           0                0                   0   
2016-12-22           0                0                   0   

            CDLXSIDEGAP3METHODS  
date                             
2016-12-28                    0  
2016-12-27                    0  
2016-12-26                    0  
2016-12-23                    0  
2016-12-22                    0  

[5 rows x 65 columns]

In [18]:
map(lambda x:nonzero(ldkg.iloc[x]),range(len(ldkg)))

[(array([0, 1, 2, 3]),),
 (array([0, 1, 2, 3]),),
 (array([0, 1, 2, 3]),),
 (array([0, 1, 2, 3]),),
 (array([0, 1, 2, 3]),),
 (array([0, 1, 2, 3]),),
 (array([0, 1, 2, 3]),),
 (array([ 0,  1,  2,  3, 44]),),
 (array([ 0,  1,  2,  3, 22]),),
 (array([0, 1, 2, 3]),),
 (array([ 0,  1,  2,  3, 15, 42]),),
 (array([0, 1, 2, 3]),),
 (array([0, 1, 2, 3]),),
 (array([0, 1, 2, 3]),),
 (array([ 0,  1,  2,  3, 22, 42]),),
 (array([ 0,  1,  2,  3, 29]),),
 (array([ 0,  1,  2,  3, 22, 32, 54]),),
 (array([ 0,  1,  2,  3, 31, 55]),),
 (array([0, 1, 2, 3]),),
 (array([ 0,  1,  2,  3, 22]),),
 (array([ 0,  1,  2,  3, 31, 55]),),
 (array([ 0,  1,  2,  3, 54]),),
 (array([ 0,  1,  2,  3, 32]),),
 (array([ 0,  1,  2,  3, 19, 31, 41, 50, 55]),),
 (array([ 0,  1,  2,  3, 22]),),
 (array([ 0,  1,  2,  3,  8, 13]),),
 (array([ 0,  1,  2,  3, 19, 27, 41, 54]),),
 (array([ 0,  1,  2,  3, 19, 26, 37, 41, 54]),),
 (array([ 0,  1,  2,  3, 54]),),
 (array([ 0,  1,  2,  3, 19, 21, 27, 41, 54, 58]),),
 (array([ 0,  

In [21]:
ldkg.iloc[661]

open                     5.75
high                     5.75
close                    5.75
low                      5.75
CDL2CROWS                0.00
CDL3BLACKCROWS           0.00
CDL3INSIDE               0.00
CDL3LINESTRIKE           0.00
CDL3OUTSIDE              0.00
CDL3STARSINSOUTH         0.00
CDL3WHITESOLDIERS        0.00
CDLABANDONEDBABY         0.00
CDLADVANCEBLOCK          0.00
CDLBELTHOLD              0.00
CDLBREAKAWAY             0.00
CDLCLOSINGMARUBOZU       0.00
CDLCONCEALBABYSWALL      0.00
CDLCOUNTERATTACK         0.00
CDLDARKCLOUDCOVER        0.00
CDLDOJI                100.00
CDLDOJISTAR              0.00
CDLDRAGONFLYDOJI         0.00
CDLENGULFING             0.00
CDLEVENINGDOJISTAR       0.00
CDLEVENINGSTAR           0.00
CDLGAPSIDESIDEWHITE      0.00
CDLGRAVESTONEDOJI        0.00
CDLHAMMER                0.00
CDLHANGINGMAN            0.00
CDLHARAMI                0.00
                        ...  
CDLIDENTICAL3CROWS       0.00
CDLINNECK                0.00
CDLINVERTE